### ISSUE TITLE
pyatv-webserver.py errors

### ISSUE THREAD

**Issue by joshtbernstein** [13mralex/c4-pyatv-remote#9]
Running the latest pyatv docker container, I'm recently getting the following errors:

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pyatv-webserver.py", line 96, in _handler
    return await method(request, atv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/pyatv-webserver.py", line 312, in artwork
    return web.Response(body=bytes(status.bytes))
                                   ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'bytes'

**Comment by 13mralex** [comment]
Hey there, sorry it's been a minute. Looks like artwork is missing from the specific media. This is addressed in the most recent version :)
